{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk-kmp/0.3.0-alpha.6/sdk-kmp-0.3.0-alpha.6.module",
    "group": "com.twinskin",
    "module": "sdk-kmp",
    "version": "0.3.0-alpha.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core.aar",
          "url": "sdk-core-0.3.0-alpha.6.aar",
          "size": 3166554,
          "sha512": "2a3a1515b8fd3e943d740e46d4071f2088b0f0ae79e741bc37b2277b69eb8b2cd1dbe32c3e3f8dd294cce4f4462301cfe569b781616a0fa4f6e35bcf47be24df",
          "sha256": "1c7a70dddfa4abdc55e448a69845b7b0a984fbff0ffb36dc7cdbe8d8af1172f0",
          "sha1": "4ddeec920c9a37780e910199d212ad5e90f99521",
          "md5": "20ad30730fb4a3b90a8becfa625f4625"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-android",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "app.cash.sqldelight",
          "module": "android-driver",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.11.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "io.github.sceneview",
          "module": "sceneview",
          "version": {
            "requires": "4.22.0"
          }
        },
        {
          "group": "com.twinskin",
          "module": "photosphere-capture",
          "version": {
            "requires": "0.3.0-alpha.6"
          }
        },
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "app.cash.sqldelight",
          "module": "coroutines-extensions",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-backhandler",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "com.powersync",
          "module": "core",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core.aar",
          "url": "sdk-core-0.3.0-alpha.6.aar",
          "size": 3166554,
          "sha512": "2a3a1515b8fd3e943d740e46d4071f2088b0f0ae79e741bc37b2277b69eb8b2cd1dbe32c3e3f8dd294cce4f4462301cfe569b781616a0fa4f6e35bcf47be24df",
          "sha256": "1c7a70dddfa4abdc55e448a69845b7b0a984fbff0ffb36dc7cdbe8d8af1172f0",
          "sha1": "4ddeec920c9a37780e910199d212ad5e90f99521",
          "md5": "20ad30730fb4a3b90a8becfa625f4625"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "sdk-core-android-0.3.0-alpha.6-sources.jar",
          "url": "sdk-core-0.3.0-alpha.6-sources.jar",
          "size": 655322,
          "sha512": "7fdf06ecaf65d94bb02be81ff17e7dd5794e37849e2e989296c7170d1c5b88d0019228c4923cd7f0350c0f029691736be18b7122c883fdc8e1571361bb5d5f72",
          "sha256": "b70a39c3512415496fc93e47507cab4ff0e2cd788e7fbff9e69fae8ded5c1c4c",
          "sha1": "ac5a928cd18d48bee9aae368f1669a6048a9ba79",
          "md5": "86ab8096c559535f783057f78a5155ff"
        }
      ]
    }
  ]
}
