{
  "formatVersion": "1.1",
  "component": {
    "group": "com.twinskin",
    "module": "photosphere-capture",
    "version": "0.1.0-alpha.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "photosphere-capture-0.1.0-alpha.13.aar",
          "url": "photosphere-capture-0.1.0-alpha.13.aar",
          "size": 25914601,
          "sha512": "935c623f39123748e0b3e52d9b1764289a00fa7d646007140d19c472922b4fd1666fb2a8f3a88a2e926c52fc0148e1fe449a55832100fda1244eef551a5603d4",
          "sha256": "081f9f1ccc47f8e90b6038f1a8ea1d99a0c7c76ee4a2747dc7fa091a0de2ab26",
          "sha1": "a1699fa106596228c5af478247297c269a51d071",
          "md5": "05cf7472b2118b50ee833cd6b87e8088"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "photosphere-capture-0.1.0-alpha.13.aar",
          "url": "photosphere-capture-0.1.0-alpha.13.aar",
          "size": 25914601,
          "sha512": "935c623f39123748e0b3e52d9b1764289a00fa7d646007140d19c472922b4fd1666fb2a8f3a88a2e926c52fc0148e1fe449a55832100fda1244eef551a5603d4",
          "sha256": "081f9f1ccc47f8e90b6038f1a8ea1d99a0c7c76ee4a2747dc7fa091a0de2ab26",
          "sha1": "a1699fa106596228c5af478247297c269a51d071",
          "md5": "05cf7472b2118b50ee833cd6b87e8088"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "photosphere-capture-0.1.0-alpha.13-sources.jar",
          "url": "photosphere-capture-0.1.0-alpha.13-sources.jar",
          "size": 71565,
          "sha512": "440836b9147f9835374b0bd92b38cc7dc56e51fe6a82498e1f1d97c9e15cc1bd4b4e72d568680893d7250456e165ce472fbddffb8a0d23e27412ad01173bc05d",
          "sha256": "74e6c5b191fb83dfb9146edc6f18a94313b43244122a62e4ff09d7403412d714",
          "sha1": "bc93d9878f755feef0f890786eb5398ce87cc882",
          "md5": "e470f68b95013c435dd4230708861fb2"
        }
      ]
    }
  ]
}
