{
  "formatVersion": "1.1",
  "component": {
    "group": "com.twinskin",
    "module": "photosphere-capture",
    "version": "0.1.0-alpha.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "photosphere-capture-0.1.0-alpha.14.aar",
          "url": "photosphere-capture-0.1.0-alpha.14.aar",
          "size": 25931915,
          "sha512": "b35c95e04eec54401d98245dfcd5760b57c5db59a5d0bbc5cf7e33878f083df014058d538f63abb898f1e08cb5f827643f9b80cbba9495d211ad998d474230f7",
          "sha256": "6d387be32b4d07f2b638a40ff3351a80e587f1e34a94533eab67efbe9c984193",
          "sha1": "77d68ee6932f2c0fbc19b897184ed38541d8e5d7",
          "md5": "ca6f247ee1eea74d38f151d8a9f6fb94"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "photosphere-capture-0.1.0-alpha.14.aar",
          "url": "photosphere-capture-0.1.0-alpha.14.aar",
          "size": 25931915,
          "sha512": "b35c95e04eec54401d98245dfcd5760b57c5db59a5d0bbc5cf7e33878f083df014058d538f63abb898f1e08cb5f827643f9b80cbba9495d211ad998d474230f7",
          "sha256": "6d387be32b4d07f2b638a40ff3351a80e587f1e34a94533eab67efbe9c984193",
          "sha1": "77d68ee6932f2c0fbc19b897184ed38541d8e5d7",
          "md5": "ca6f247ee1eea74d38f151d8a9f6fb94"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "photosphere-capture-0.1.0-alpha.14-sources.jar",
          "url": "photosphere-capture-0.1.0-alpha.14-sources.jar",
          "size": 77880,
          "sha512": "30fd31eb47f8f8f15034c73863003811abc3b3ac96785d39fc8406a7e8b427d259a6d0d1734234748212553abc24c9ed479efcdb7f6cb3629e1851a7b781f6dd",
          "sha256": "936a408caf90e956df6935f682bb924b9ea0d29717c7110fe5b5ef2c4624151d",
          "sha1": "323dd2eff0366560a140b49f30480925a6e3d90f",
          "md5": "77a44f40a6c3d15062af90182064b7d4"
        }
      ]
    }
  ]
}
