{
  "formatVersion": "1.1",
  "component": {
    "group": "com.twinskin",
    "module": "photosphere-capture",
    "version": "0.1.0-alpha.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "photosphere-capture-0.1.0-alpha.16.aar",
          "url": "photosphere-capture-0.1.0-alpha.16.aar",
          "size": 25932484,
          "sha512": "300aaf035081d64133b8c79d76f0f7e217442b4c76806483fa59cc1eb7bad704f67c74e8e06e40bd74f9f2f130441ec5fa2f122a0590dd8fb753a5046462faa7",
          "sha256": "90a8b3ed35730fecd1eff5d29d2bd1611ff70abd28f143306785f68e11e9d38b",
          "sha1": "65e4c99b7232b922f653e1db213f03c09b61244e",
          "md5": "4917b3d8d276b51e2dfcab57535d54cb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "photosphere-capture-0.1.0-alpha.16.aar",
          "url": "photosphere-capture-0.1.0-alpha.16.aar",
          "size": 25932484,
          "sha512": "300aaf035081d64133b8c79d76f0f7e217442b4c76806483fa59cc1eb7bad704f67c74e8e06e40bd74f9f2f130441ec5fa2f122a0590dd8fb753a5046462faa7",
          "sha256": "90a8b3ed35730fecd1eff5d29d2bd1611ff70abd28f143306785f68e11e9d38b",
          "sha1": "65e4c99b7232b922f653e1db213f03c09b61244e",
          "md5": "4917b3d8d276b51e2dfcab57535d54cb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "photosphere-capture-0.1.0-alpha.16-sources.jar",
          "url": "photosphere-capture-0.1.0-alpha.16-sources.jar",
          "size": 77903,
          "sha512": "a3ea2e77bb770fc8828927c79a4f5811d2e283b5ccbb523757af298f1381ae03068109c4e7817522e96ac7f0cf3de0077a803bcd1d9f9c7745f7bf9ffe88a094",
          "sha256": "b89390d66b2a248ef096db2ae4081b223233b54c05fdd37bb765305d97436bcb",
          "sha1": "988e29854cd3c1c34504411f164764ec527fb804",
          "md5": "a5a8da6e3851675c14675501b0ef5a7a"
        }
      ]
    }
  ]
}
