{
  "formatVersion": "1.1",
  "component": {
    "group": "com.twinskin",
    "module": "photosphere-capture",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "photosphere-capture-0.1.1.aar",
          "url": "photosphere-capture-0.1.1.aar",
          "size": 24878482,
          "sha512": "a2786c7d2e49d63dfb1af10f9f58734230f2053d64067ea2d6a2c14effd52756fea63af897175222ca4504bae7a8a6d9ece08353b5753c21779b5b66668c8381",
          "sha256": "122445f79e9f55f89d536a6f1c871406cd1a1648a90190b5cdcebb69c03f17ff",
          "sha1": "7184fd032d5baa65665799ec1fab6e560a3331fd",
          "md5": "1f6302dcbdc9a94508829efb0d5336fc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "photosphere-capture-0.1.1.aar",
          "url": "photosphere-capture-0.1.1.aar",
          "size": 24878482,
          "sha512": "a2786c7d2e49d63dfb1af10f9f58734230f2053d64067ea2d6a2c14effd52756fea63af897175222ca4504bae7a8a6d9ece08353b5753c21779b5b66668c8381",
          "sha256": "122445f79e9f55f89d536a6f1c871406cd1a1648a90190b5cdcebb69c03f17ff",
          "sha1": "7184fd032d5baa65665799ec1fab6e560a3331fd",
          "md5": "1f6302dcbdc9a94508829efb0d5336fc"
        }
      ]
    }
  ]
}
