{
  "formatVersion": "1.1",
  "component": {
    "group": "com.twinskin",
    "module": "sdk",
    "version": "0.1.0-alpha.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.twinskin",
          "module": "sdk-kmp",
          "version": {
            "requires": "0.1.0-alpha.16"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-0.1.0-alpha.16.aar",
          "url": "sdk-0.1.0-alpha.16.aar",
          "size": 15896265,
          "sha512": "5387e8699a948688449d0e7cff5555a91d7690b5ba75c875292c3a7870a5ac7701305cb792add390743de0c53a23f3314595316474400cc4bfa4500bc2eee701",
          "sha256": "d14c193e498cfd41440f823f3fa4a7b9bc3543193091ca23fcb1f9b6e32229e8",
          "sha1": "230256667dbd8b3f140279088c0dbffbb178f3d1",
          "md5": "b24dfe8b120438832a1861ea426861b4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "com.twinskin",
          "module": "sdk-kmp",
          "version": {
            "requires": "0.1.0-alpha.16"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-0.1.0-alpha.16.aar",
          "url": "sdk-0.1.0-alpha.16.aar",
          "size": 15896265,
          "sha512": "5387e8699a948688449d0e7cff5555a91d7690b5ba75c875292c3a7870a5ac7701305cb792add390743de0c53a23f3314595316474400cc4bfa4500bc2eee701",
          "sha256": "d14c193e498cfd41440f823f3fa4a7b9bc3543193091ca23fcb1f9b6e32229e8",
          "sha1": "230256667dbd8b3f140279088c0dbffbb178f3d1",
          "md5": "b24dfe8b120438832a1861ea426861b4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-0.1.0-alpha.16-sources.jar",
          "url": "sdk-0.1.0-alpha.16-sources.jar",
          "size": 10828,
          "sha512": "60d698a44227ee2deba57d82b16b1734eef9d2f32981422bab0d57d12b9cb050741573470b37acc2c58ebcb543884eeeef6c9bb382617b529cf7c0934a128a81",
          "sha256": "3fc4aa3cc22075420fe58888af9b930959c56c7bf08863a99c65e27a3a6571ac",
          "sha1": "fe658e4c731284ac1ed1ece865acd13449eb6aca",
          "md5": "52f778612fe218c5de7fcdd96a6cb454"
        }
      ]
    }
  ]
}
