{
  "formatVersion": "1.1",
  "component": {
    "group": "com.twinskin",
    "module": "sdk",
    "version": "0.3.0-alpha.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.twinskin",
          "module": "sdk-kmp",
          "version": {
            "requires": "0.3.0-alpha.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-0.3.0-alpha.4.aar",
          "url": "sdk-0.3.0-alpha.4.aar",
          "size": 16066186,
          "sha512": "81371a431b905071d7a115c697adfd7707a11ca8dfb34c572b2636d6bb67c21cc30154845d0a4cfbc78a4c8c9eac816249856a71384b57255a26b3816ca199c5",
          "sha256": "5791b8c645713fcb00d2a67b79c5d16c3b3b20f48250eb915a5aee6ec12301a1",
          "sha1": "3f17cdb63b143fc5137356dcfec4e60096bb2fc1",
          "md5": "3d915d912dcb8021c39d1211fff475f7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "com.twinskin",
          "module": "sdk-kmp",
          "version": {
            "requires": "0.3.0-alpha.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-0.3.0-alpha.4.aar",
          "url": "sdk-0.3.0-alpha.4.aar",
          "size": 16066186,
          "sha512": "81371a431b905071d7a115c697adfd7707a11ca8dfb34c572b2636d6bb67c21cc30154845d0a4cfbc78a4c8c9eac816249856a71384b57255a26b3816ca199c5",
          "sha256": "5791b8c645713fcb00d2a67b79c5d16c3b3b20f48250eb915a5aee6ec12301a1",
          "sha1": "3f17cdb63b143fc5137356dcfec4e60096bb2fc1",
          "md5": "3d915d912dcb8021c39d1211fff475f7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-0.3.0-alpha.4-sources.jar",
          "url": "sdk-0.3.0-alpha.4-sources.jar",
          "size": 14257,
          "sha512": "e6d65fe949f8add6a5f802efb572e1d27dcfa6857e6a4da21c4b47b65c0aa0f041ebe7e7fab975fc8a6d6c8db83c0926301940a55f3298c33e01dbf6fd5da3ff",
          "sha256": "70dcec27ac26e8d78370be960cade45c246eef4e895cd5265f17c02859c2e89a",
          "sha1": "b9e1b32ec124c1099f913efc901ad324bfe1e168",
          "md5": "dd2098e9c89aad13882ebca95ddcf37d"
        }
      ]
    }
  ]
}
