{
  "formatVersion": "1.1",
  "component": {
    "group": "com.twinskin",
    "module": "sdk",
    "version": "0.3.0-alpha.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.twinskin",
          "module": "sdk-kmp",
          "version": {
            "requires": "0.3.0-alpha.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-0.3.0-alpha.3.aar",
          "url": "sdk-0.3.0-alpha.3.aar",
          "size": 16065857,
          "sha512": "d89dd3005ddfdc4bd6513b06e524c9df6f8cc39eebff6165a30247872c56b0da7a33398bb806edb6e5e86110b9b1f58ec02b01e93bfbcb85c2e5827538b23482",
          "sha256": "4afa8fd2461efa1fcf7824e34c364d6653a02a61e3fe9e9b2319b2a2d9e7d81c",
          "sha1": "6329e3e6601727b4b3bda334494e80950975aa26",
          "md5": "d7955af72207122f000c87707ce3fa3e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "com.twinskin",
          "module": "sdk-kmp",
          "version": {
            "requires": "0.3.0-alpha.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-0.3.0-alpha.3.aar",
          "url": "sdk-0.3.0-alpha.3.aar",
          "size": 16065857,
          "sha512": "d89dd3005ddfdc4bd6513b06e524c9df6f8cc39eebff6165a30247872c56b0da7a33398bb806edb6e5e86110b9b1f58ec02b01e93bfbcb85c2e5827538b23482",
          "sha256": "4afa8fd2461efa1fcf7824e34c364d6653a02a61e3fe9e9b2319b2a2d9e7d81c",
          "sha1": "6329e3e6601727b4b3bda334494e80950975aa26",
          "md5": "d7955af72207122f000c87707ce3fa3e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-0.3.0-alpha.3-sources.jar",
          "url": "sdk-0.3.0-alpha.3-sources.jar",
          "size": 13660,
          "sha512": "b70e7bca03016e1aec45720fb2f1f2a28048f453d3090ed81b2285a19cb235224675eba28fb76d1aedddd71f1c1ca5c4bc6529cfd7b688c2ce8a17dc02fb1490",
          "sha256": "ef48cbc17300c87fdbdd8bfaa8695615a6e3b91d9b7851dd78a2fb823c0faa37",
          "sha1": "d60cfd62b5ac92c224b9f58262e5d7fda139208b",
          "md5": "8a3c75ee4a32fd2d29058fca34ece282"
        }
      ]
    }
  ]
}
