{
  "formatVersion": "1.1",
  "component": {
    "group": "com.twinskin",
    "module": "photosphere-capture",
    "version": "0.3.0-alpha.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "photosphere-capture-0.3.0-alpha.6.aar",
          "url": "photosphere-capture-0.3.0-alpha.6.aar",
          "size": 25095975,
          "sha512": "a486d250c4fdbb9640dcf99603b5552cbd7d1b02cf5944e2b1c24671222f59a8b10a292bb622a332b6e164748e4e6f9e3273dbce83715a6f3d4f7acec7394d50",
          "sha256": "132967474d0286d2a5f0865505156fee272028f637f0674df38428fe1510d5e3",
          "sha1": "dab861c331a7058bf0fdd887ab0cca3139fafa4a",
          "md5": "528f00f3b4f0bddacf8e0736cdf18bdd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "photosphere-capture-0.3.0-alpha.6.aar",
          "url": "photosphere-capture-0.3.0-alpha.6.aar",
          "size": 25095975,
          "sha512": "a486d250c4fdbb9640dcf99603b5552cbd7d1b02cf5944e2b1c24671222f59a8b10a292bb622a332b6e164748e4e6f9e3273dbce83715a6f3d4f7acec7394d50",
          "sha256": "132967474d0286d2a5f0865505156fee272028f637f0674df38428fe1510d5e3",
          "sha1": "dab861c331a7058bf0fdd887ab0cca3139fafa4a",
          "md5": "528f00f3b4f0bddacf8e0736cdf18bdd"
        }
      ]
    }
  ]
}
