{
  "formatVersion": "1.1",
  "component": {
    "group": "com.twinskin",
    "module": "sdk-kmp",
    "version": "0.1.0-alpha.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "app.cash.sqldelight",
          "module": "coroutines-extensions",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "com.powersync",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "app.cash.sqldelight",
          "module": "native-driver",
          "version": {
            "requires": "2.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-metadata-0.1.0-alpha.15.jar",
          "url": "sdk-kmp-0.1.0-alpha.15.jar",
          "size": 163423,
          "sha512": "ab75401ee07487a4d650cdb672ff887eec36472090e25314e0b576cb171556563bd5ff5331b10ee66a1944a04155a83ca5c76b21c8e13eb5f614dbf0cfe3813c",
          "sha256": "357555ec57d534f4ef3e33ff7e425f517914bef423d0e9ca018fe71eda487b76",
          "sha1": "f381432a299b9a199adb0f596e1dee9a8f635136",
          "md5": "2115e0eb739debe75fa112952626404e"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "sdk-core-kotlin-0.1.0-alpha.15-sources.jar",
          "url": "sdk-kmp-0.1.0-alpha.15-sources.jar",
          "size": 379558,
          "sha512": "f4f1ef3ed07ed682a3bc6742273dbfb48bd7d961c2110d62e3ecda2b6ee54fe28ffc1e387e51e9623d4893d4b9e59bad4e3eef2767d4ea3e6d2f6b1b16cd34f0",
          "sha256": "54f6cc8ad6a5d31f555fbe5c369162e289aebe7b9ceb9f06f171cba0a4bd3d05",
          "sha1": "38e708c6f132f994546f4d118607aeb35c06667a",
          "md5": "183f195af130b248244c1c713faba8b7"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../sdk-core/0.1.0-alpha.15/sdk-core-0.1.0-alpha.15.module",
        "group": "com.twinskin",
        "module": "sdk-core",
        "version": "0.1.0-alpha.15"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../sdk-core/0.1.0-alpha.15/sdk-core-0.1.0-alpha.15.module",
        "group": "com.twinskin",
        "module": "sdk-core",
        "version": "0.1.0-alpha.15"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../sdk-core/0.1.0-alpha.15/sdk-core-0.1.0-alpha.15.module",
        "group": "com.twinskin",
        "module": "sdk-core",
        "version": "0.1.0-alpha.15"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../shared-iosarm64/0.1.0-alpha.15/shared-iosarm64-0.1.0-alpha.15.module",
        "group": "com.twinskin",
        "module": "shared-iosarm64",
        "version": "0.1.0-alpha.15"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../shared-iosarm64/0.1.0-alpha.15/shared-iosarm64-0.1.0-alpha.15.module",
        "group": "com.twinskin",
        "module": "shared-iosarm64",
        "version": "0.1.0-alpha.15"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../shared-iosarm64/0.1.0-alpha.15/shared-iosarm64-0.1.0-alpha.15.module",
        "group": "com.twinskin",
        "module": "shared-iosarm64",
        "version": "0.1.0-alpha.15"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../shared-iosarm64/0.1.0-alpha.15/shared-iosarm64-0.1.0-alpha.15.module",
        "group": "com.twinskin",
        "module": "shared-iosarm64",
        "version": "0.1.0-alpha.15"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../shared-iossimulatorarm64/0.1.0-alpha.15/shared-iossimulatorarm64-0.1.0-alpha.15.module",
        "group": "com.twinskin",
        "module": "shared-iossimulatorarm64",
        "version": "0.1.0-alpha.15"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../shared-iossimulatorarm64/0.1.0-alpha.15/shared-iossimulatorarm64-0.1.0-alpha.15.module",
        "group": "com.twinskin",
        "module": "shared-iossimulatorarm64",
        "version": "0.1.0-alpha.15"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../shared-iossimulatorarm64/0.1.0-alpha.15/shared-iossimulatorarm64-0.1.0-alpha.15.module",
        "group": "com.twinskin",
        "module": "shared-iossimulatorarm64",
        "version": "0.1.0-alpha.15"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../shared-iossimulatorarm64/0.1.0-alpha.15/shared-iossimulatorarm64-0.1.0-alpha.15.module",
        "group": "com.twinskin",
        "module": "shared-iossimulatorarm64",
        "version": "0.1.0-alpha.15"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../shared-jvm/0.1.0-alpha.15/shared-jvm-0.1.0-alpha.15.module",
        "group": "com.twinskin",
        "module": "shared-jvm",
        "version": "0.1.0-alpha.15"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../shared-jvm/0.1.0-alpha.15/shared-jvm-0.1.0-alpha.15.module",
        "group": "com.twinskin",
        "module": "shared-jvm",
        "version": "0.1.0-alpha.15"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../shared-jvm/0.1.0-alpha.15/shared-jvm-0.1.0-alpha.15.module",
        "group": "com.twinskin",
        "module": "shared-jvm",
        "version": "0.1.0-alpha.15"
      }
    }
  ]
}
