{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk-kmp/0.1.1/sdk-kmp-0.1.1.module",
    "group": "com.twinskin",
    "module": "sdk-kmp",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core.aar",
          "url": "sdk-core-0.1.1.aar",
          "size": 2538798,
          "sha512": "bedd66982fc39574cd97ae3d0c7447d6e4000060a651db07cd104f2f5b931a681d722271c8e193a4fd02eb1e0aaccc752bab7817c8fa6337c32c4b8a5f162bb8",
          "sha256": "9b9412ac18dfafbedd42c551304d036918c71284bc7f9e2eff7b5c56064c316f",
          "sha1": "6a224c9337cd4117f118085a4a75b0e4f5cc9f32",
          "md5": "edc895606bd30adae09343f000a9ccf7"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-android",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "app.cash.sqldelight",
          "module": "android-driver",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.11.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "io.github.sceneview",
          "module": "sceneview",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.twinskin",
          "module": "photosphere-capture",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "app.cash.sqldelight",
          "module": "coroutines-extensions",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "com.powersync",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core.aar",
          "url": "sdk-core-0.1.1.aar",
          "size": 2538798,
          "sha512": "bedd66982fc39574cd97ae3d0c7447d6e4000060a651db07cd104f2f5b931a681d722271c8e193a4fd02eb1e0aaccc752bab7817c8fa6337c32c4b8a5f162bb8",
          "sha256": "9b9412ac18dfafbedd42c551304d036918c71284bc7f9e2eff7b5c56064c316f",
          "sha1": "6a224c9337cd4117f118085a4a75b0e4f5cc9f32",
          "md5": "edc895606bd30adae09343f000a9ccf7"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "sdk-core-android-0.1.1-sources.jar",
          "url": "sdk-core-0.1.1-sources.jar",
          "size": 520682,
          "sha512": "eb149125b84c0aa9eacdbfacd1ec628cec82234b6b8883a362b25dc9d8cb95bef8e7a5f06bff450e906ce3f7e771d3ed0d298ceb2cff6137951d3995178855e3",
          "sha256": "c7bb21fe71227271863f4e5264007cd8046805074b911891f1cde688897d6387",
          "sha1": "21a5292ee361184734bdf652f2d2bee582b59fef",
          "md5": "d6eea72fc82940bc35f49165f8a10029"
        }
      ]
    }
  ]
}
