{
  "formatVersion": "1.1",
  "component": {
    "group": "com.twinskin",
    "module": "photosphere-capture",
    "version": "0.3.0-alpha.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "photosphere-capture-0.3.0-alpha.1.aar",
          "url": "photosphere-capture-0.3.0-alpha.1.aar",
          "size": 24880609,
          "sha512": "00f06a18256d5603c4f535d3031bbd91970f3099a06782417416a5216ca4b1c50e698b6a55ff98cc1e391634a674a028694c7c2e0f60737a4fa81d1800343750",
          "sha256": "7e2c76038da16afeb18f81c3c5e72ad084dff13d826a4996a29dcb05f32987c1",
          "sha1": "586897734a4113a580b0bf82ee2712381b199cc4",
          "md5": "7ad82a9f46e4f91dbbbd594fb9b3003d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "photosphere-capture-0.3.0-alpha.1.aar",
          "url": "photosphere-capture-0.3.0-alpha.1.aar",
          "size": 24880609,
          "sha512": "00f06a18256d5603c4f535d3031bbd91970f3099a06782417416a5216ca4b1c50e698b6a55ff98cc1e391634a674a028694c7c2e0f60737a4fa81d1800343750",
          "sha256": "7e2c76038da16afeb18f81c3c5e72ad084dff13d826a4996a29dcb05f32987c1",
          "sha1": "586897734a4113a580b0bf82ee2712381b199cc4",
          "md5": "7ad82a9f46e4f91dbbbd594fb9b3003d"
        }
      ]
    }
  ]
}
