{
  "formatVersion": "1.1",
  "component": {
    "group": "com.twinskin",
    "module": "photosphere-capture",
    "version": "0.3.0-alpha.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "photosphere-capture-0.3.0-alpha.5.aar",
          "url": "photosphere-capture-0.3.0-alpha.5.aar",
          "size": 25095979,
          "sha512": "2c07b131c9d25ffacb8c9f52c45bf4205f2fbbfa34d0fdb64d5658145b5ed04106b0d6ef4eadf994365ea8c719faa28d2ecd471f634b54b7f9585e788d4afcfd",
          "sha256": "e4e9da3d9d0201ab27cfea7fd90cb8afac3b8c1f1540ff0a4654d9ca160819fa",
          "sha1": "6cf9a21e21d8392a4e05b26820e3578de12e58e5",
          "md5": "ec4ba9405421bd1891df89ed6eeab4ba"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "photosphere-capture-0.3.0-alpha.5.aar",
          "url": "photosphere-capture-0.3.0-alpha.5.aar",
          "size": 25095979,
          "sha512": "2c07b131c9d25ffacb8c9f52c45bf4205f2fbbfa34d0fdb64d5658145b5ed04106b0d6ef4eadf994365ea8c719faa28d2ecd471f634b54b7f9585e788d4afcfd",
          "sha256": "e4e9da3d9d0201ab27cfea7fd90cb8afac3b8c1f1540ff0a4654d9ca160819fa",
          "sha1": "6cf9a21e21d8392a4e05b26820e3578de12e58e5",
          "md5": "ec4ba9405421bd1891df89ed6eeab4ba"
        }
      ]
    }
  ]
}
