{
  "formatVersion": "1.1",
  "component": {
    "group": "com.twinskin",
    "module": "photosphere-capture",
    "version": "0.3.0-alpha.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "photosphere-capture-0.3.0-alpha.4.aar",
          "url": "photosphere-capture-0.3.0-alpha.4.aar",
          "size": 25096032,
          "sha512": "f7a8e20e65f8c6ae81a771421792ef59792628fcf41e52aebed213c7d1c75bfa46c26325a5ee95113e526e753df41df51f5dee0f64916fa7157b1cdc82b3a0ad",
          "sha256": "3d55d30f7fab1d52c5d0568053bea6ce27604b19505b7689bbc49d70030c9b38",
          "sha1": "4365cfb56893ef9bb169807b454fbcbc9f77ac3e",
          "md5": "9a9513c5dff460b07c250f5af2d68d5f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "photosphere-capture-0.3.0-alpha.4.aar",
          "url": "photosphere-capture-0.3.0-alpha.4.aar",
          "size": 25096032,
          "sha512": "f7a8e20e65f8c6ae81a771421792ef59792628fcf41e52aebed213c7d1c75bfa46c26325a5ee95113e526e753df41df51f5dee0f64916fa7157b1cdc82b3a0ad",
          "sha256": "3d55d30f7fab1d52c5d0568053bea6ce27604b19505b7689bbc49d70030c9b38",
          "sha1": "4365cfb56893ef9bb169807b454fbcbc9f77ac3e",
          "md5": "9a9513c5dff460b07c250f5af2d68d5f"
        }
      ]
    }
  ]
}
