{
  "formatVersion": "1.1",
  "component": {
    "group": "com.twinskin",
    "module": "sdk",
    "version": "0.1.0-alpha.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.twinskin",
          "module": "sdk-kmp",
          "version": {
            "requires": "0.1.0-alpha.17"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-0.1.0-alpha.17.aar",
          "url": "sdk-0.1.0-alpha.17.aar",
          "size": 15896263,
          "sha512": "e713525b5e1f60d29cdcb7d2a2de209c8cc03acf4f8b7256da589b9c9d5ae590593898f9240f7dc3aa5694af8c56954eac172e4f66deee4a2eb97df7bba34227",
          "sha256": "312cdaa74cc980c15073ecc0119ef067bcb29447790952dede82c1ab62711d09",
          "sha1": "dffc99aa9f69c446b5d468471d117a9bf091d215",
          "md5": "dba110c61d9f472bfb617a58adcb41fd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "com.twinskin",
          "module": "sdk-kmp",
          "version": {
            "requires": "0.1.0-alpha.17"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-0.1.0-alpha.17.aar",
          "url": "sdk-0.1.0-alpha.17.aar",
          "size": 15896263,
          "sha512": "e713525b5e1f60d29cdcb7d2a2de209c8cc03acf4f8b7256da589b9c9d5ae590593898f9240f7dc3aa5694af8c56954eac172e4f66deee4a2eb97df7bba34227",
          "sha256": "312cdaa74cc980c15073ecc0119ef067bcb29447790952dede82c1ab62711d09",
          "sha1": "dffc99aa9f69c446b5d468471d117a9bf091d215",
          "md5": "dba110c61d9f472bfb617a58adcb41fd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-0.1.0-alpha.17-sources.jar",
          "url": "sdk-0.1.0-alpha.17-sources.jar",
          "size": 10828,
          "sha512": "60d698a44227ee2deba57d82b16b1734eef9d2f32981422bab0d57d12b9cb050741573470b37acc2c58ebcb543884eeeef6c9bb382617b529cf7c0934a128a81",
          "sha256": "3fc4aa3cc22075420fe58888af9b930959c56c7bf08863a99c65e27a3a6571ac",
          "sha1": "fe658e4c731284ac1ed1ece865acd13449eb6aca",
          "md5": "52f778612fe218c5de7fcdd96a6cb454"
        }
      ]
    }
  ]
}
