{
  "formatVersion": "1.1",
  "component": {
    "group": "com.twinskin",
    "module": "photosphere-capture",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "photosphere-capture-0.2.1.aar",
          "url": "photosphere-capture-0.2.1.aar",
          "size": 24880574,
          "sha512": "3a17ce42362f5c4c4771c7e9ffac0216668b065c492ed6f236cba3dcd5cd349c7992eb180314ec790c6ec438e7325667a73a309550b18456b87656331891acd5",
          "sha256": "8505ff3b29808a865905dca5958ed3dd9fe5c89390d40ea7bb5bddb5d20fab1d",
          "sha1": "943f65658be3ef35ced9a085f640d2c624b96ef8",
          "md5": "4853f4dd7a7c5d62536f9cc528842f8c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "photosphere-capture-0.2.1.aar",
          "url": "photosphere-capture-0.2.1.aar",
          "size": 24880574,
          "sha512": "3a17ce42362f5c4c4771c7e9ffac0216668b065c492ed6f236cba3dcd5cd349c7992eb180314ec790c6ec438e7325667a73a309550b18456b87656331891acd5",
          "sha256": "8505ff3b29808a865905dca5958ed3dd9fe5c89390d40ea7bb5bddb5d20fab1d",
          "sha1": "943f65658be3ef35ced9a085f640d2c624b96ef8",
          "md5": "4853f4dd7a7c5d62536f9cc528842f8c"
        }
      ]
    }
  ]
}
