{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk-kmp/0.1.0-alpha.11/sdk-kmp-0.1.0-alpha.11.module",
    "group": "com.twinskin",
    "module": "sdk-kmp",
    "version": "0.1.0-alpha.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core.aar",
          "url": "sdk-core-0.1.0-alpha.11.aar",
          "size": 1773094,
          "sha512": "acc8ff49cd40189b40d1e83e9d28ad25cce1b5ef3e0a1cb81bb78cf2c000b3f0aeb9d0331e699fdf5a32f492b2c536902a36782507092b20103c31a9dc8022c6",
          "sha256": "410e3ad8d85670a1e6512f90fb143ca3629fb3b360959e05e87fd0d46c44bb23",
          "sha1": "21467a3053a7e38601be8dd43a6d85f48a4256de",
          "md5": "3b5a5929d50de29b258eb4a248a77348"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-android",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "app.cash.sqldelight",
          "module": "android-driver",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.12.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "io.github.sceneview",
          "module": "sceneview",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.twinskin",
          "module": "photosphere-capture",
          "version": {
            "requires": "0.1.0-alpha.11"
          }
        },
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "app.cash.sqldelight",
          "module": "coroutines-extensions",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.6"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.6"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.powersync",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core.aar",
          "url": "sdk-core-0.1.0-alpha.11.aar",
          "size": 1773094,
          "sha512": "acc8ff49cd40189b40d1e83e9d28ad25cce1b5ef3e0a1cb81bb78cf2c000b3f0aeb9d0331e699fdf5a32f492b2c536902a36782507092b20103c31a9dc8022c6",
          "sha256": "410e3ad8d85670a1e6512f90fb143ca3629fb3b360959e05e87fd0d46c44bb23",
          "sha1": "21467a3053a7e38601be8dd43a6d85f48a4256de",
          "md5": "3b5a5929d50de29b258eb4a248a77348"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "sdk-core-android-0.1.0-alpha.11-sources.jar",
          "url": "sdk-core-0.1.0-alpha.11-sources.jar",
          "size": 367339,
          "sha512": "f33c5eeddf14a0a83a34c6865c12ab166552cdd696cfb75f03e01fcfc5b0f8aba956ce630b4c8fd89b861aa9fc1541ac7a7d1f885371e00ee8cc1761c671e3cb",
          "sha256": "cc04159633495befb60c60d45faea7884b6287a7c60e0e73e033322626358262",
          "sha1": "10ba8e51d6c90564e56b9823ba203342ce08cc17",
          "md5": "1c864e8d42c562e4aa91063aece1dbf7"
        }
      ]
    }
  ]
}
