{
  "formatVersion": "1.1",
  "component": {
    "group": "com.twinskin",
    "module": "photosphere-capture",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "photosphere-capture-0.1.0.aar",
          "url": "photosphere-capture-0.1.0.aar",
          "size": 24878465,
          "sha512": "21aca637e32f53c2b0c73fbea666dafd9a15c9237008389c36721ced6bc8800a706bf56a2ad3c4fd4e2457dbbb7593bbf8664ac0edde6a16a8817c38c1704458",
          "sha256": "2e263b22c331469608170c9d1c15600728db7272dc471af81476c46a554908d6",
          "sha1": "9ebdbc41f2a937e230b5236009fef6fba4466935",
          "md5": "3dfdcafb2523bead4acaf046ddb2d57f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "photosphere-capture-0.1.0.aar",
          "url": "photosphere-capture-0.1.0.aar",
          "size": 24878465,
          "sha512": "21aca637e32f53c2b0c73fbea666dafd9a15c9237008389c36721ced6bc8800a706bf56a2ad3c4fd4e2457dbbb7593bbf8664ac0edde6a16a8817c38c1704458",
          "sha256": "2e263b22c331469608170c9d1c15600728db7272dc471af81476c46a554908d6",
          "sha1": "9ebdbc41f2a937e230b5236009fef6fba4466935",
          "md5": "3dfdcafb2523bead4acaf046ddb2d57f"
        }
      ]
    }
  ]
}
