{
  "formatVersion": "1.1",
  "component": {
    "group": "com.twinskin",
    "module": "sdk",
    "version": "0.1.0-alpha.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.twinskin",
          "module": "sdk-kmp",
          "version": {
            "requires": "0.1.0-alpha.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-0.1.0-alpha.4.aar",
          "url": "sdk-0.1.0-alpha.4.aar",
          "size": 14026,
          "sha512": "538e2d76e1d21430a6b8a74e50c8847ecaeccbfab66a7eb3dadba9e96143e8c25f0e0cd8f4518af7341729b9be06db693cdb87b6c4c20091da0bec6493e1e8d0",
          "sha256": "64dc1ea8f33c3d80e8f405a16da728c71353927f88d95b324eaa4e0d5213705c",
          "sha1": "b821c1119cad2474582800b1abf95941c8f1c409",
          "md5": "9c22a3d600a693f81896cd6f51cc4bb5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.12.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.twinskin",
          "module": "sdk-kmp",
          "version": {
            "requires": "0.1.0-alpha.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-0.1.0-alpha.4.aar",
          "url": "sdk-0.1.0-alpha.4.aar",
          "size": 14026,
          "sha512": "538e2d76e1d21430a6b8a74e50c8847ecaeccbfab66a7eb3dadba9e96143e8c25f0e0cd8f4518af7341729b9be06db693cdb87b6c4c20091da0bec6493e1e8d0",
          "sha256": "64dc1ea8f33c3d80e8f405a16da728c71353927f88d95b324eaa4e0d5213705c",
          "sha1": "b821c1119cad2474582800b1abf95941c8f1c409",
          "md5": "9c22a3d600a693f81896cd6f51cc4bb5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-0.1.0-alpha.4-sources.jar",
          "url": "sdk-0.1.0-alpha.4-sources.jar",
          "size": 3805,
          "sha512": "e62458a160e9a4c29b2e21e5395179ba88d5e2b3b68f73ff901b5f5c2d92df26d69c4f896a8f1db7cd2043cb988f603d49c975520e7907d6a09f6d585db4766d",
          "sha256": "afe0befe1146b32394fe3b30a4c78c5df17a434e068e54f625420dc16dec613e",
          "sha1": "781de32d81e64b7b58a1c70ead7a1dc864e0a47e",
          "md5": "8900b4182a6aa2186c0b355956265f24"
        }
      ]
    }
  ]
}
