{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk-kmp/0.3.0-alpha.1/sdk-kmp-0.3.0-alpha.1.module",
    "group": "com.twinskin",
    "module": "sdk-kmp",
    "version": "0.3.0-alpha.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core.aar",
          "url": "sdk-core-0.3.0-alpha.1.aar",
          "size": 2671328,
          "sha512": "dc0b5c9a31bf45b4a7222715d18e6db6bd4ea18d3bd05899b71e22c8adcac4f53c638f85c199dde8296fcd83ba3cd6c62e2f1b2a8cab014e7830930e77b371e9",
          "sha256": "d36a616ff642ec5e54ca4cb033b2538720002d07506b39e803d6aae1dfc601d0",
          "sha1": "1d148994c192ef107fa326e4b6ffc47b0cdc2f54",
          "md5": "de3abda4fea1179fbee1146322163624"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-android",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "app.cash.sqldelight",
          "module": "android-driver",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.11.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "io.github.sceneview",
          "module": "sceneview",
          "version": {
            "requires": "4.18.0"
          }
        },
        {
          "group": "com.twinskin",
          "module": "photosphere-capture",
          "version": {
            "requires": "0.3.0-alpha.1"
          }
        },
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "app.cash.sqldelight",
          "module": "coroutines-extensions",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "com.powersync",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core.aar",
          "url": "sdk-core-0.3.0-alpha.1.aar",
          "size": 2671328,
          "sha512": "dc0b5c9a31bf45b4a7222715d18e6db6bd4ea18d3bd05899b71e22c8adcac4f53c638f85c199dde8296fcd83ba3cd6c62e2f1b2a8cab014e7830930e77b371e9",
          "sha256": "d36a616ff642ec5e54ca4cb033b2538720002d07506b39e803d6aae1dfc601d0",
          "sha1": "1d148994c192ef107fa326e4b6ffc47b0cdc2f54",
          "md5": "de3abda4fea1179fbee1146322163624"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "sdk-core-android-0.3.0-alpha.1-sources.jar",
          "url": "sdk-core-0.3.0-alpha.1-sources.jar",
          "size": 537609,
          "sha512": "f416a8d5084012780f91024653cc37d5ceae0c5845ec1af35ff4bd9858e390e3444d26d2182f327514aa3e75f689cc92909dba3695d41739a2c53f020f86d7da",
          "sha256": "3166669ebb616eb34a871777fcc3321bf01d392da6ddc4ba73c1e05933fba363",
          "sha1": "5127067c92b1af08cee0337214b04dec81c45d54",
          "md5": "c97f3ee09b91132fef563c4dc562d1e9"
        }
      ]
    }
  ]
}
