{
  "formatVersion": "1.1",
  "component": {
    "group": "com.twinskin",
    "module": "capture-probes",
    "version": "0.3.0-alpha.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "capture-probes-0.3.0-alpha.10.aar",
          "url": "capture-probes-0.3.0-alpha.10.aar",
          "size": 2400770,
          "sha512": "68304f2c811462d5baea88561f4761b8029b021e9a526dba3d5f0289af7b2e5a4fbaa5dac29552dd011a1d984d708f26a4211193ffdc6e424ce1358057eabb1e",
          "sha256": "f8a50be605b8f19df2dbc24d5bb48287da66870b0823b0c2b63abac4f0313656",
          "sha1": "3da4760572a57d33b0219b4840a2f1ac513ca47f",
          "md5": "83ba68927f9aa60bce591f7b394bf3f6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "capture-probes-0.3.0-alpha.10.aar",
          "url": "capture-probes-0.3.0-alpha.10.aar",
          "size": 2400770,
          "sha512": "68304f2c811462d5baea88561f4761b8029b021e9a526dba3d5f0289af7b2e5a4fbaa5dac29552dd011a1d984d708f26a4211193ffdc6e424ce1358057eabb1e",
          "sha256": "f8a50be605b8f19df2dbc24d5bb48287da66870b0823b0c2b63abac4f0313656",
          "sha1": "3da4760572a57d33b0219b4840a2f1ac513ca47f",
          "md5": "83ba68927f9aa60bce591f7b394bf3f6"
        }
      ]
    }
  ]
}
