{
  "formatVersion": "1.1",
  "component": {
    "group": "com.twinskin",
    "module": "photosphere-capture",
    "version": "0.3.0-alpha.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "photosphere-capture-0.3.0-alpha.3.aar",
          "url": "photosphere-capture-0.3.0-alpha.3.aar",
          "size": 24880656,
          "sha512": "d3cb3eb14d1a725f131ac61cc60f6a074b552d2330860134a46f3858e45a56fe666f396b8625d32b2716f4bb7a42a76c9b6f00e96a46b53321b5a3ea312deba4",
          "sha256": "8d0fe81fce52c31261aa51393dbd8ebeb9b1d2f6ffa5dcca039eb2fcdd498e67",
          "sha1": "a6def5e79ccab34d005063e98369ff26a3376e48",
          "md5": "aae6473fff9a6853a6dd65d8bcea8801"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "photosphere-capture-0.3.0-alpha.3.aar",
          "url": "photosphere-capture-0.3.0-alpha.3.aar",
          "size": 24880656,
          "sha512": "d3cb3eb14d1a725f131ac61cc60f6a074b552d2330860134a46f3858e45a56fe666f396b8625d32b2716f4bb7a42a76c9b6f00e96a46b53321b5a3ea312deba4",
          "sha256": "8d0fe81fce52c31261aa51393dbd8ebeb9b1d2f6ffa5dcca039eb2fcdd498e67",
          "sha1": "a6def5e79ccab34d005063e98369ff26a3376e48",
          "md5": "aae6473fff9a6853a6dd65d8bcea8801"
        }
      ]
    }
  ]
}
