{
  "formatVersion": "1.1",
  "component": {
    "group": "com.twinskin",
    "module": "sdk",
    "version": "0.1.0-alpha.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.twinskin",
          "module": "sdk-kmp",
          "version": {
            "requires": "0.1.0-alpha.15"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-0.1.0-alpha.15.aar",
          "url": "sdk-0.1.0-alpha.15.aar",
          "size": 15895787,
          "sha512": "abe54ea7fb9cc0d1de99a4f5abe955da7767240e14bcc865400e3380b12fe6134e0e344b3da0cd0ec5a021f8c0d159ffce411bab6f9106d0cc18d2a67636a6b6",
          "sha256": "eed2c6fa9000c43a1a1852b97bf0bf53996e49cff769a31da9b785fb97764b84",
          "sha1": "4ff936455c544cde54268de1effc547cda3cdb17",
          "md5": "ce12512787db5196c7ed8fdb2866af96"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "com.twinskin",
          "module": "sdk-kmp",
          "version": {
            "requires": "0.1.0-alpha.15"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-0.1.0-alpha.15.aar",
          "url": "sdk-0.1.0-alpha.15.aar",
          "size": 15895787,
          "sha512": "abe54ea7fb9cc0d1de99a4f5abe955da7767240e14bcc865400e3380b12fe6134e0e344b3da0cd0ec5a021f8c0d159ffce411bab6f9106d0cc18d2a67636a6b6",
          "sha256": "eed2c6fa9000c43a1a1852b97bf0bf53996e49cff769a31da9b785fb97764b84",
          "sha1": "4ff936455c544cde54268de1effc547cda3cdb17",
          "md5": "ce12512787db5196c7ed8fdb2866af96"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-0.1.0-alpha.15-sources.jar",
          "url": "sdk-0.1.0-alpha.15-sources.jar",
          "size": 10100,
          "sha512": "6afde3a57bb41d8daea2cf3a7871bee41f0e58320406051676b5a3bc8d4069b0528f912c163a13f3a937d8eef56e23d317b12372196272ddeef8a386ce38d01c",
          "sha256": "132b86c4d46c1287096d6e6589ae287c711c04f80edd018a6c07de800ac34aee",
          "sha1": "2b8939d6d5bff004b2767fc287b3ac6269a7fa55",
          "md5": "26d3296f450219116db48c4585ba2640"
        }
      ]
    }
  ]
}
