{
  "formatVersion": "1.1",
  "component": {
    "group": "com.twinskin",
    "module": "photosphere-capture",
    "version": "0.1.0-alpha.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "photosphere-capture-0.1.0-alpha.11.aar",
          "url": "photosphere-capture-0.1.0-alpha.11.aar",
          "size": 22428456,
          "sha512": "005d3c5b154e3d55ea45be2b059ab2da0be969e15d8700e4360003aef160856cd1e2a4249596c2c5755f5b8b023caf976bcd0ad15673b09b237fe3fc7c98a9b2",
          "sha256": "a914ecbdfee5eaf4178ff2c9a432eddd546e7c652e9c77e491bc7f50f709729d",
          "sha1": "2b5637389742f34a8d83bed4f8af9901493a8336",
          "md5": "ab28ed7a74f2e1021af21a4c30b12336"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.microsoft.onnxruntime",
          "module": "onnxruntime-android",
          "version": {
            "requires": "1.22.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "photosphere-capture-0.1.0-alpha.11.aar",
          "url": "photosphere-capture-0.1.0-alpha.11.aar",
          "size": 22428456,
          "sha512": "005d3c5b154e3d55ea45be2b059ab2da0be969e15d8700e4360003aef160856cd1e2a4249596c2c5755f5b8b023caf976bcd0ad15673b09b237fe3fc7c98a9b2",
          "sha256": "a914ecbdfee5eaf4178ff2c9a432eddd546e7c652e9c77e491bc7f50f709729d",
          "sha1": "2b5637389742f34a8d83bed4f8af9901493a8336",
          "md5": "ab28ed7a74f2e1021af21a4c30b12336"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "photosphere-capture-0.1.0-alpha.11-sources.jar",
          "url": "photosphere-capture-0.1.0-alpha.11-sources.jar",
          "size": 71565,
          "sha512": "440836b9147f9835374b0bd92b38cc7dc56e51fe6a82498e1f1d97c9e15cc1bd4b4e72d568680893d7250456e165ce472fbddffb8a0d23e27412ad01173bc05d",
          "sha256": "74e6c5b191fb83dfb9146edc6f18a94313b43244122a62e4ff09d7403412d714",
          "sha1": "bc93d9878f755feef0f890786eb5398ce87cc882",
          "md5": "e470f68b95013c435dd4230708861fb2"
        }
      ]
    }
  ]
}
