{
  "formatVersion": "1.1",
  "component": {
    "group": "com.twinskin",
    "module": "photosphere-capture",
    "version": "0.1.0-alpha.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "photosphere-capture-0.1.0-alpha.15.aar",
          "url": "photosphere-capture-0.1.0-alpha.15.aar",
          "size": 25932475,
          "sha512": "c43ec1ae513398d8f4fc6ec8e25e577971565d70f9e4423d888ffe5e1b957aa3bf9c00201457bd845939cf078962c882d73ad8e0d10c02e4af1d18a5aa393fc8",
          "sha256": "91780a366bc651d67e490adb52f4e0eb09666f4bb5d4a726a125683bf8ebe42c",
          "sha1": "b45f4462f8415edc3352cf41681eca6f8054144f",
          "md5": "e2129fe07284d38dd1ca24097dd0a3e0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "photosphere-capture-0.1.0-alpha.15.aar",
          "url": "photosphere-capture-0.1.0-alpha.15.aar",
          "size": 25932475,
          "sha512": "c43ec1ae513398d8f4fc6ec8e25e577971565d70f9e4423d888ffe5e1b957aa3bf9c00201457bd845939cf078962c882d73ad8e0d10c02e4af1d18a5aa393fc8",
          "sha256": "91780a366bc651d67e490adb52f4e0eb09666f4bb5d4a726a125683bf8ebe42c",
          "sha1": "b45f4462f8415edc3352cf41681eca6f8054144f",
          "md5": "e2129fe07284d38dd1ca24097dd0a3e0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "photosphere-capture-0.1.0-alpha.15-sources.jar",
          "url": "photosphere-capture-0.1.0-alpha.15-sources.jar",
          "size": 77903,
          "sha512": "a3ea2e77bb770fc8828927c79a4f5811d2e283b5ccbb523757af298f1381ae03068109c4e7817522e96ac7f0cf3de0077a803bcd1d9f9c7745f7bf9ffe88a094",
          "sha256": "b89390d66b2a248ef096db2ae4081b223233b54c05fdd37bb765305d97436bcb",
          "sha1": "988e29854cd3c1c34504411f164764ec527fb804",
          "md5": "a5a8da6e3851675c14675501b0ef5a7a"
        }
      ]
    }
  ]
}
