{
  "formatVersion": "1.1",
  "component": {
    "group": "com.twinskin",
    "module": "photosphere-capture",
    "version": "0.3.0-alpha.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "photosphere-capture-0.3.0-alpha.7.aar",
          "url": "photosphere-capture-0.3.0-alpha.7.aar",
          "size": 25413149,
          "sha512": "060d371af8bc847f1a814ea215dda973c26ee109c14933352b113dbae03a34af82c5226de0dc7001062b380be3ee6af95a4a4afe02608110fbb3ec6da297a7cd",
          "sha256": "fbd6fa5d9eb2d963bc337e9cdb79b4ec156bc792fb0bf544ec5f8b458ad7095c",
          "sha1": "5b352faf529e9c5fc292b663c10a5b12785df44b",
          "md5": "0ee96586634e676dc95df027643871a3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "photosphere-capture-0.3.0-alpha.7.aar",
          "url": "photosphere-capture-0.3.0-alpha.7.aar",
          "size": 25413149,
          "sha512": "060d371af8bc847f1a814ea215dda973c26ee109c14933352b113dbae03a34af82c5226de0dc7001062b380be3ee6af95a4a4afe02608110fbb3ec6da297a7cd",
          "sha256": "fbd6fa5d9eb2d963bc337e9cdb79b4ec156bc792fb0bf544ec5f8b458ad7095c",
          "sha1": "5b352faf529e9c5fc292b663c10a5b12785df44b",
          "md5": "0ee96586634e676dc95df027643871a3"
        }
      ]
    }
  ]
}
